#!/bin/bash
# status-rollup.sh — Generate/update portfolio dashboard
# Scans engagements/ for engagement.yaml and _phase.yaml files
# Produces/updates engagements/_portfolio-dashboard.md

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../../" && pwd)"
ENGAGEMENTS_DIR="${REPO_ROOT}/engagements"
DASHBOARD="${ENGAGEMENTS_DIR}/_portfolio-dashboard.md"
TODAY=$(date +%Y-%m-%d)
NOW=$(date +%Y-%m-%dT%H:%M:%S)

echo "Generating portfolio dashboard..."

# ── Helper: extract YAML value ─────────────────────────────────────────────────
yaml_value() {
  local file="$1"
  local key="$2"
  grep "^${key}:" "${file}" 2>/dev/null | head -1 | sed 's/^[^:]*: *//' | sed 's/"//g' | sed "s/'//g" | xargs
}

# ── Collect engagement data ────────────────────────────────────────────────────
ENGAGEMENT_ROWS=""
TOTAL_ENGAGEMENTS=0
ACTIVE_COUNT=0
COMPLETED_COUNT=0

while IFS= read -r -d '' eng_yaml; do
  dir=$(dirname "${eng_yaml}")
  name=$(yaml_value "${eng_yaml}" "name")
  client=$(yaml_value "${eng_yaml}" "client")
  status=$(yaml_value "${eng_yaml}" "status")
  phase=$(yaml_value "${eng_yaml}" "current_phase")
  slug=$(yaml_value "${eng_yaml}" "slug")
  dl=$(yaml_value "${eng_yaml}" "delivery_lead")
  created=$(yaml_value "${eng_yaml}" "created")

  # Skip example engagement in output (but still count)
  if [[ "${slug}" == "_example"* ]]; then
    continue
  fi

  TOTAL_ENGAGEMENTS=$((TOTAL_ENGAGEMENTS + 1))
  [[ "${status}" == "active" ]] && ACTIVE_COUNT=$((ACTIVE_COUNT + 1))
  [[ "${status}" == "completed" ]] && COMPLETED_COUNT=$((COMPLETED_COUNT + 1))

  # Calculate overall completion
  total_deliverables=0
  completed_deliverables=0
  while IFS= read -r -d '' phase_yaml; do
    # Count deliverables in each phase yaml
    phase_total=$(grep -c "status:" "${phase_yaml}" 2>/dev/null || echo "0")
    phase_done=$(grep -c "status: completed" "${phase_yaml}" 2>/dev/null || echo "0")
    total_deliverables=$((total_deliverables + phase_total - 1))  # -1 for phase-level status
    completed_deliverables=$((completed_deliverables + phase_done))
  done < <(find "${dir}" -name "_phase.yaml" -print0 2>/dev/null)

  completion="—"
  if [[ ${total_deliverables} -gt 0 ]]; then
    pct=$(( (completed_deliverables * 100) / total_deliverables ))
    completion="${pct}%"
  fi

  rel_path="engagements/${slug}"
  ENGAGEMENT_ROWS="${ENGAGEMENT_ROWS}| [${name}](${rel_path}/README.md) | ${client} | ${status} | ${phase} | ${dl:-—} | ${created} | ${completion} |\n"
done < <(find "${ENGAGEMENTS_DIR}" -mindepth 2 -maxdepth 2 -name "engagement.yaml" -not -path "*/_*" -print0 2>/dev/null)

# ── Write dashboard ────────────────────────────────────────────────────────────
cat > "${DASHBOARD}" <<DASHBOARD
---
title: "Portfolio Dashboard"
type: status-update
date: "${TODAY}"
last_updated: "${NOW}"
tags:
  - portfolio
  - status-update
  - status:approved
status: approved
generated_by: status-rollup
---

# Portfolio Dashboard

*Auto-generated by \`status-rollup.sh\` on ${NOW}*

## Summary

| Metric | Value |
|--------|-------|
| Total engagements | ${TOTAL_ENGAGEMENTS} |
| Active | ${ACTIVE_COUNT} |
| Completed | ${COMPLETED_COUNT} |
| Last updated | ${NOW} |

## Engagement Portfolio

| Engagement | Client | Status | Current Phase | Delivery Lead | Created | Completion |
|-----------|--------|--------|--------------|--------------|---------|-----------|
DASHBOARD

if [[ -n "${ENGAGEMENT_ROWS}" ]]; then
  printf "%b" "${ENGAGEMENT_ROWS}" >> "${DASHBOARD}"
else
  echo "| — | No engagements found | — | — | — | — | — |" >> "${DASHBOARD}"
fi

cat >> "${DASHBOARD}" <<'DASHBOARD'

## Phase Legend

| Phase | Description |
|-------|-------------|
| discover-envision | Scope, feasibility, SoW definition |
| design-implement | Build, govern, and deliver |
| run-evolve | Operate and continuously improve |

## Status Legend

| Status | Meaning |
|--------|---------|
| active | Engagement in progress |
| on-hold | Temporarily paused |
| completed | Engagement closed |
| cancelled | Engagement cancelled |

---
*Run `npm run delivery:status` to regenerate this dashboard.*
DASHBOARD

echo "Dashboard written to: ${DASHBOARD}"
echo "  Total engagements found: ${TOTAL_ENGAGEMENTS}"
