#!/bin/bash
# tag-manager.sh — Scan tags and generate tag-index.md
# Scans frontmatter tags across engagements/ and knowledge/
# Generates knowledge/tag-index.md with tag names, counts, and file lists

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../../" && pwd)"
OUTPUT_FILE="${REPO_ROOT}/knowledge/tag-index.md"
TODAY=$(date +%Y-%m-%d)
NOW=$(date +%Y-%m-%dT%H:%M:%S)

echo "Scanning tags across repository..."

# ── Collect all tags from frontmatter ─────────────────────────────────────────
declare -A TAG_COUNTS
declare -A TAG_FILES

while IFS= read -r -d '' filepath; do
  [[ "${filepath}" == *".gitkeep" ]] && continue

  # Only process files with frontmatter
  if ! head -1 "${filepath}" | grep -q "^---"; then
    continue
  fi

  # Extract tags from frontmatter
  in_frontmatter=false
  in_tags=false
  while IFS= read -r line; do
    if [[ "${line}" == "---" ]]; then
      if [[ "${in_frontmatter}" == "false" ]]; then
        in_frontmatter=true
        continue
      else
        break
      fi
    fi

    if [[ "${in_frontmatter}" == "true" ]]; then
      # Detect tags section
      if echo "${line}" | grep -q "^tags:"; then
        in_tags=true
        # Check for inline tags: tags: [tag1, tag2]
        if echo "${line}" | grep -q "\["; then
          tags_inline=$(echo "${line}" | sed 's/^tags: *//' | tr -d '[]' | tr ',' '\n')
          while IFS= read -r tag; do
            tag=$(echo "${tag}" | xargs | tr -d '"' | tr -d "'")
            [[ -z "${tag}" ]] && continue
            TAG_COUNTS["${tag}"]=$(( ${TAG_COUNTS["${tag}"]:-0} + 1 ))
            rel_path="${filepath#${REPO_ROOT}/}"
            TAG_FILES["${tag}"]="${TAG_FILES["${tag}"]:-}${rel_path}|"
          done <<< "${tags_inline}"
          in_tags=false
        fi
        continue
      fi

      # In tags list (YAML list items starting with -)
      if [[ "${in_tags}" == "true" ]]; then
        if echo "${line}" | grep -q "^  - "; then
          tag=$(echo "${line}" | sed 's/^  - //' | xargs | tr -d '"' | tr -d "'")
          [[ -z "${tag}" ]] && continue
          TAG_COUNTS["${tag}"]=$(( ${TAG_COUNTS["${tag}"]:-0} + 1 ))
          rel_path="${filepath#${REPO_ROOT}/}"
          TAG_FILES["${tag}"]="${TAG_FILES["${tag}"]:-}${rel_path}|"
        elif ! echo "${line}" | grep -q "^  "; then
          in_tags=false
        fi
      fi
    fi
  done < "${filepath}"
done < <(find "${REPO_ROOT}/engagements" "${REPO_ROOT}/knowledge" -name "*.md" -type f -print0 2>/dev/null)

# ── Sort tags by count (descending) ───────────────────────────────────────────
TOTAL_TAGS=${#TAG_COUNTS[@]}
echo "  Found ${TOTAL_TAGS} unique tags."

# ── Write tag-index.md ─────────────────────────────────────────────────────────
mkdir -p "$(dirname "${OUTPUT_FILE}")"

cat > "${OUTPUT_FILE}" <<HEADER
---
title: "Tag Index"
type: knowledge
date: "${TODAY}"
last_updated: "${NOW}"
tags:
  - meta
  - tag-index
status: approved
generated_by: tag-manager
---

# Tag Index

*Auto-generated by \`tag-manager.sh\` on ${NOW}*

**Total unique tags:** ${TOTAL_TAGS}

---

## Tag Summary

| Tag | Count |
|-----|-------|
HEADER

# Sort tags by count descending
for tag in $(for k in "${!TAG_COUNTS[@]}"; do echo "${TAG_COUNTS[$k]} ${k}"; done | sort -rn | awk '{print $2}'); do
  count=${TAG_COUNTS["${tag}"]}
  echo "| \`${tag}\` | ${count} |" >> "${OUTPUT_FILE}"
done

cat >> "${OUTPUT_FILE}" <<'SECTION'

---

## Tag Details

SECTION

# Output details for each tag
for tag in $(for k in "${!TAG_COUNTS[@]}"; do echo "${TAG_COUNTS[$k]} ${k}"; done | sort -rn | awk '{print $2}'); do
  count=${TAG_COUNTS["${tag}"]}
  echo "### \`${tag}\` (${count} files)" >> "${OUTPUT_FILE}"
  echo "" >> "${OUTPUT_FILE}"

  IFS='|' read -ra files <<< "${TAG_FILES["${tag}"]}"
  for f in "${files[@]}"; do
    [[ -z "${f}" ]] && continue
    echo "- [${f}](/${f})" >> "${OUTPUT_FILE}"
  done
  echo "" >> "${OUTPUT_FILE}"
done

echo "" >> "${OUTPUT_FILE}"
echo "---" >> "${OUTPUT_FILE}"
echo "*Run \`npm run delivery:tags\` to regenerate this index.*" >> "${OUTPUT_FILE}"

echo "Tag index written to: ${OUTPUT_FILE}"
