/**
 * JSON Schema for validating the agent YAML configuration
 */
export interface AgentSchema1D0D0 {
    /**
     * YAML schema version
     */
    version: '1.0.0';
    /**
     * The name of the agent.
     */
    name: string;
    /**
     * The description of the agent.
     */
    description?: null | string;
    /**
     * Metadata about the agent
     */
    metadata?: Metadata;
    /**
     * Agent id is a unique identifier for the agent. This field is auto generated by Azure AI
     * Foundry Agent Service after deployment.
     */
    id?: null | string;
    /**
     * The ID of the model to use for the agent.
     */
    model: Model;
    /**
     * Give your agent clear directions on what to do and how to do it. Include specific tasks,
     * their order, and any special instructions like tone or engagement style.
     */
    instructions: null | string;
    /**
     * A set of resources that are used by the agent's tools. The resources are specific to the
     * type of tool. For example, the `code_interpreter` tool requires a list of file IDs, while
     * the `file_search` tool requires a list of vector store IDs.
     */
    tools?: Tool[];
}
/**
 * Metadata about the agent
 */
export interface Metadata {
    /**
     * Author name
     */
    authors?: string[];
    /**
     * Agent tag
     */
    tags?: string[];
    [property: string]: any;
}
/**
 * The ID of the model to use for the agent.
 */
export interface Model {
    /**
     * Model deploy name
     */
    id: string;
    /**
     * Options for the model
     */
    options?: ModelOptions;
}
/**
 * Options for the model
 */
export interface ModelOptions {
    /**
     * What sampling temperature to use, between 0 and 1. Higher values like 0.8 will make the
     * output more random, while lower values like 0.2 will make it more focused and
     * deterministic.
     */
    temperature?: number | null;
    /**
     * An alternative to sampling with temperature, called nucleus sampling, where the model
     * considers the results of the tokens with top_p probability mass. So 0.1 means only the
     * tokens comprising the top 10% probability mass are considered. We generally recommend
     * altering this or temperature but not both.
     */
    top_p?: number | null;
}
/**
 * The input definition information for a bing grounding search tool as used to configure an
 * agent.
 *
 * Code Interpreter tool configuration. Code interpreter is a tool that can read and
 * interpret information from datasets, generate code, and create graphs and charts.
 *
 * The input definition information for an OpenAPI tool as used to configure an agent
 *
 * File Search tool configuration. Add your own files to augment the agent with specialized
 * knowledge. Files will be added to a vector store that the search index can reference for
 * quick information retrieval. Encrypted or sensitivity-labeled files are not supported.
 */
export interface Tool {
    /**
     * The object type, which is always 'bing_grounding'.
     *
     * Tool type must be 'code_interpreter'
     *
     * The object type, which is always 'openapi'.
     *
     * The object type, which is always 'file_search'.
     */
    type: Type;
    /**
     * Identifier for Bing Grounding
     *
     * Identifier for the code interpreter tool
     *
     * Tool identifier for OpenAPI tool
     *
     * Tool identifier for File Search
     */
    id?: null | string;
    /**
     * Options for bing grounding tool
     *
     * Options for code_interpreter tool
     *
     * Options for openapi tool
     *
     * Options for file_search tool
     */
    options?: ToolOptions;
    /**
     * A description of what the function does, used by the model to choose when and how to call
     * the function.
     */
    description?: null | string;
}
/**
 * Options for bing grounding tool
 *
 * Options for code_interpreter tool
 *
 * Options for openapi tool
 *
 * Options for file_search tool
 *
 * Options for mcp tool
 */
export interface ToolOptions {
    /**
     * The list of connections used by the bing grounding tool.
     */
    tool_connections?: string[];
    /**
     * List of file id used by the code interpreter
     */
    file_ids?: string[];
    /**
     * The openapi function shape, described as a JSON Schema object.
     */
    specification?: string;
    /**
     * Open API authentication details
     */
    auth?: Auth;
    /**
     * List of vector store identifiers
     */
    vector_store_ids?: string[];
    /** The language to use for user interface strings when calling Bing API. */
    set_lang?: string;
    /** Filter search results by a specific time range. Accepted values: https://learn.microsoft.com/bing/search-apis/bing-web-search/reference/query-parameters */
    freshness?: string;
    /** The number of search results to return in the bing api response */
    count?: number;
    /** The market where the results come from. */
    market?: string;
    /**
     * The URL of the MCP server
     */
    server_url?: string;
    /**
     * The label of the MCP server
     */
    server_label?: string;
    /**
     * The list of allowed tools
     */
    allowed_tools?: string[];
}
/**
 * Open API authentication details
 */
export interface Auth {
    /**
     * Authentication type for OpenAPI tool
     */
    type: string;
    [property: string]: any;
}
export type Type = 'bing_grounding' | 'code_interpreter' | 'openapi' | 'file_search' | 'mcp';
export declare class Convert {
    static toAgentSchema1D0D0(json: string): AgentSchema1D0D0;
    static agentSchema1D0D0ToJson(value: AgentSchema1D0D0): string;
}
//# sourceMappingURL=AgentSchema1D0D0.d.ts.map