"""
Document Management System
Tracks changes to Knowledge documents with automatic logging in PostgreSQL
"""

import hashlib
import json
import os
from pathlib import Path
from datetime import datetime
from typing import Optional, Dict, Any
import psycopg2
from psycopg2.extras import Json
import logging

logger = logging.getLogger(__name__)


class DocumentManager:
    """Manages document tracking, versioning, and change logging."""
    
    def __init__(self, knowledge_dir: str, db_connection_string: str):
        """
        Initialize document manager.
        
        Args:
            knowledge_dir: Path to Knowledge folder
            db_connection_string: PostgreSQL connection string
        """
        self.knowledge_dir = Path(knowledge_dir)
        self.db_conn_string = db_connection_string
        self.logger = logging.getLogger(f"{__name__}.DocumentManager")
    
    def compute_hash(self, content: bytes) -> str:
        """
        Compute SHA256 hash of file content.
        
        Args:
            content: File bytes
            
        Returns:
            Hex digest of SHA256 hash
        """
        return hashlib.sha256(content).hexdigest()
    
    def register_document(self, relative_path: str, ai_generated: bool = False,
                         tags: Optional[list] = None) -> int:
        """
        Register a document in the database.
        
        Args:
            relative_path: Path relative to Knowledge directory
            ai_generated: Whether document was generated by AI agent
            tags: Optional list of tags for categorization
            
        Returns:
            Document ID in database
            
        Raises:
            FileNotFoundError: If document doesn't exist
        """
        full_path = self.knowledge_dir / relative_path
        
        if not full_path.exists():
            raise FileNotFoundError(f"Document not found: {full_path}")
        
        # Read content and compute hash
        content = full_path.read_bytes()
        content_hash = self.compute_hash(content)
        file_stat = full_path.stat()
        
        # Determine file type from extension
        file_type = full_path.suffix.lstrip('.')
        if not file_type:
            file_type = 'other'
        
        try:
            with psycopg2.connect(self.db_conn_string) as conn:
                with conn.cursor() as cur:
                    # Insert or update document
                    cur.execute("""
                        INSERT INTO documents
                        (name, path, type, content_hash, tags, ai_generated, 
                         created_by, size_bytes)
                        VALUES 
                        (%s, %s, %s, %s, %s, %s,
                         (SELECT id FROM users WHERE identifier = %s),
                         %s)
                        ON CONFLICT (path) DO UPDATE
                        SET content_hash = EXCLUDED.content_hash,
                            updated_at = NOW(),
                            tags = COALESCE(EXCLUDED.tags, documents.tags)
                        RETURNING id
                    """, (
                        full_path.name,
                        relative_path,
                        file_type,
                        content_hash,
                        tags,
                        ai_generated,
                        'system',
                        file_stat.st_size
                    ))
                    doc_id = cur.fetchone()[0]
                    conn.commit()
                    
                    self.logger.info(f"Registered document {relative_path} (ID: {doc_id})")
                    return doc_id
                    
        except psycopg2.Error as e:
            self.logger.error(f"Database error registering document: {e}")
            raise
    
    def log_change(self, relative_path: str, change_type: str,
                   previous_hash: Optional[str] = None,
                   new_hash: Optional[str] = None,
                   change_description: Optional[str] = None,
                   change_reason: str = 'manual_edit',
                   trace_id: Optional[str] = None,
                   metadata_changes: Optional[Dict] = None) -> int:
        """
        Log a document change.
        
        Args:
            relative_path: Path to document
            change_type: 'created', 'modified', 'deleted', 'restored'
            previous_hash: Hash before change
            new_hash: Hash after change
            change_description: Human-readable description of change
            change_reason: Reason for change (agent_modification, manual_edit, auto_backup, etc)
            trace_id: OpenTelemetry trace ID for linking
            metadata_changes: Changes to metadata
            
        Returns:
            Change log entry ID
        """
        try:
            with psycopg2.connect(self.db_conn_string) as conn:
                with conn.cursor() as cur:
                    # Find document
                    cur.execute("SELECT id FROM documents WHERE path = %s", 
                               (relative_path,))
                    result = cur.fetchone()
                    
                    if not result:
                        self.logger.warning(f"Document not found for change logging: {relative_path}")
                        return None
                    
                    doc_id = result[0]
                    
                    # Insert change log entry
                    cur.execute("""
                        INSERT INTO document_changes
                        (document_id, change_type, previous_hash, new_hash,
                         change_description, change_reason, trace_id,
                         metadata_changes, changed_by, change_timestamp)
                        VALUES 
                        (%s, %s, %s, %s, %s, %s, %s, %s,
                         (SELECT id FROM users WHERE identifier = %s),
                         NOW())
                        RETURNING id
                    """, (
                        doc_id,
                        change_type,
                        previous_hash,
                        new_hash,
                        change_description,
                        change_reason,
                        trace_id,
                        Json(metadata_changes) if metadata_changes else None,
                        'system'
                    ))
                    
                    change_id = cur.fetchone()[0]
                    conn.commit()
                    
                    self.logger.info(
                        f"Logged {change_type} for {relative_path} "
                        f"(trace_id: {trace_id})"
                    )
                    return change_id
                    
        except psycopg2.Error as e:
            self.logger.error(f"Database error logging change: {e}")
            raise
    
    def track_file_changes(self, relative_path: str) -> Dict[str, Any]:
        """
        Detect and log changes to a document.
        
        Args:
            relative_path: Path to document relative to Knowledge
            
        Returns:
            Change summary dictionary
        """
        full_path = self.knowledge_dir / relative_path
        
        if not full_path.exists():
            raise FileNotFoundError(f"Document not found: {full_path}")
        
        # Read current content
        current_content = full_path.read_bytes()
        current_hash = self.compute_hash(current_content)
        
        try:
            with psycopg2.connect(self.db_conn_string) as conn:
                with conn.cursor() as cur:
                    # Get last recorded hash
                    cur.execute(
                        "SELECT content_hash FROM documents WHERE path = %s",
                        (relative_path,)
                    )
                    result = cur.fetchone()
                    
                    if not result:
                        # New document
                        return {
                            'status': 'new',
                            'path': relative_path,
                            'new_hash': current_hash
                        }
                    
                    previous_hash = result[0]
                    
                    if current_hash == previous_hash:
                        return {
                            'status': 'unchanged',
                            'path': relative_path
                        }
                    
                    # Document changed
                    file_stat = full_path.stat()
                    
                    # Log the change
                    self.log_change(
                        relative_path,
                        'modified',
                        previous_hash=previous_hash,
                        new_hash=current_hash,
                        change_reason='auto_detect'
                    )
                    
                    return {
                        'status': 'modified',
                        'path': relative_path,
                        'previous_hash': previous_hash,
                        'new_hash': current_hash,
                        'size_bytes': file_stat.st_size
                    }
                    
        except psycopg2.Error as e:
            self.logger.error(f"Error tracking file changes: {e}")
            raise
    
    def get_document_history(self, relative_path: str, 
                            limit: int = 50) -> list:
        """
        Get change history for a document.
        
        Args:
            relative_path: Path to document
            limit: Maximum number of changes to return
            
        Returns:
            List of change records
        """
        try:
            with psycopg2.connect(self.db_conn_string) as conn:
                with conn.cursor() as cur:
                    cur.execute("""
                        SELECT 
                            dc.id, dc.change_type, dc.change_timestamp,
                            u.name as changed_by, dc.change_description,
                            dc.previous_hash, dc.new_hash, dc.trace_id
                        FROM document_changes dc
                        LEFT JOIN users u ON dc.changed_by = u.id
                        WHERE dc.document_id = (
                            SELECT id FROM documents WHERE path = %s
                        )
                        ORDER BY dc.change_timestamp DESC
                        LIMIT %s
                    """, (relative_path, limit))
                    
                    columns = [desc[0] for desc in cur.description]
                    return [dict(zip(columns, row)) for row in cur.fetchall()]
                    
        except psycopg2.Error as e:
            self.logger.error(f"Error retrieving document history: {e}")
            raise
    
    def export_audit_report(self, output_file: str = None) -> str:
        """
        Export audit report of all document changes.
        
        Args:
            output_file: Path to save report (optional)
            
        Returns:
            Report content as string
        """
        try:
            with psycopg2.connect(self.db_conn_string) as conn:
                with conn.cursor() as cur:
                    # Get document activity summary
                    cur.execute("""
                        SELECT * FROM v_document_activity
                        ORDER BY last_modified DESC
                    """)
                    
                    columns = [desc[0] for desc in cur.description]
                    rows = cur.fetchall()
                    
                    # Format report
                    report_lines = [
                        "═" * 80,
                        "DOCUMENT AUDIT REPORT",
                        f"Generated: {datetime.now().isoformat()}",
                        "═" * 80,
                        ""
                    ]
                    
                    for row in rows:
                        record = dict(zip(columns, row))
                        report_lines.append(f"📄 {record['name']}")
                        report_lines.append(f"   Path: {record['path']}")
                        report_lines.append(f"   Changes: {record['total_changes']}")
                        report_lines.append(f"   Last Modified: {record['last_modified']}")
                        report_lines.append(f"   Contributors: {record['contributors']}")
                        report_lines.append(f"   AI Generated: {record['ai_generated']}")
                        report_lines.append("")
                    
                    report = "\n".join(report_lines)
                    
                    if output_file:
                        Path(output_file).write_text(report)
                        self.logger.info(f"Audit report exported to {output_file}")
                    
                    return report
                    
        except psycopg2.Error as e:
            self.logger.error(f"Error exporting audit report: {e}")
            raise


# Convenience functions
def create_manager(knowledge_dir: str, db_connection_string: str) -> DocumentManager:
    """Factory function to create document manager."""
    return DocumentManager(knowledge_dir, db_connection_string)
