#!/usr/bin/env python3
"""
Create specialized DevOps agents from base AGENTS.md
"""

import sys
import argparse
from pathlib import Path

AGENT_TEMPLATE = """# {agent_name}

## Project Overview

{agent_name} is a specialized AI agent focused on {focus_area} for the VSCode_March26 project. 
This agent analyzes, optimizes, and automates {focus_domain} workflows.

## Core Capabilities

{capabilities}

## Tech Stack

{tech_stack}

## Architecture

This agent operates using a modular analysis pipeline:

1. **Code Analysis**: Scans relevant files for {focus_area} patterns
2. **Convention Extraction**: Identifies best practices and anti-patterns
3. **Recommendation Generation**: Proposes improvements and automations
4. **Execution**: Implements changes or generates configurations

## Tools Provided

{tools}

## Code Style & Conventions

{conventions}

## Anti-Patterns & Restrictions

{antipatterns}

## Usage Examples

{examples}

## Integration Points

- **Base codebase**: VSCode_March26
- **Generation source**: AutogenerateAgentsMD
- **Model**: DSPy + LLM (Gemini/Claude/OpenAI)
- **Update frequency**: On-demand via regeneration

---
*Generated by: DevOps Agent Specialization Pipeline*
*Base AGENTS.md: {base_agents_path}*
*Focus: {focus_area}*
"""

AGENT_SPECS = {
    "cicd": {
        "agent_name": "CI/CD Pipeline Agent",
        "focus_area": "continuous integration and deployment",
        "focus_domain": "CI/CD, build, test, and deployment",
        "capabilities": """
- Analyze GitHub Actions workflows
- Generate optimized CI/CD pipelines
- Detect workflow inefficiencies
- Implement deployment strategies (blue/green, canary)
- Manage versioning and rollbacks
- Monitor build and deployment success rates
""",
        "tech_stack": """
- GitHub Actions
- n8n (workflow automation)
- Docker (containerization)
- Git (version control)
- YAML (workflow definitions)
""",
        "tools": """
### `analyzeWorkflow`
Analyzes GitHub Actions workflow files for optimization opportunities.

**Input**: `workflow_path` (string)
**Output**: Analysis report with recommendations

### `generatePipeline`
Creates new CI/CD pipeline definitions.

**Input**: `project_type` (string), `requirements` (object)
**Output**: Complete workflow YAML

### `validateWorkflow`
Checks workflow definitions for errors and anti-patterns.

**Input**: `workflow_yaml` (string)
**Output**: Validation results with errors/warnings
""",
        "conventions": """
- Use explicit step names in workflows
- Always include timeout specifications
- Implement proper error handling
- Use secrets for credentials
- Cache dependencies when possible
""",
        "antipatterns": """
- ❌ Never commit credentials to workflow files
- ❌ Don't use deprecated GitHub Actions
- ❌ Avoid unbounded workflow runs
- ❌ Don't skip test steps in production deployments
""",
        "examples": """
**Example 1: Analyze existing workflow**
```
User: "CICDAgent, analyze my GitHub Actions workflows"
Agent: *Scans .github/workflows/*.yml*
       *Identifies 3 optimization opportunities*
       Recommendation: Add dependency caching (saves 2 min per run)
```

**Example 2: Generate new pipeline**
```
User: "CICDAgent, create a deployment pipeline for n8n"
Agent: *Generates complete workflow*
       *Includes build, test, security scan, deploy stages*
       *Saves to .github/workflows/n8n-deploy.yml*
```
""",
    },
    "infrastructure": {
        "agent_name": "Infrastructure as Code Agent",
        "focus_area": "infrastructure provisioning and management",
        "focus_domain": "cloud infrastructure, IaC, resource optimization",
        "capabilities": """
- Analyze infrastructure definitions (Terraform, Bicep, CloudFormation)
- Generate infrastructure templates
- Detect configuration drift
- Optimize resource allocation and costs
- Validate security configurations
- Manage multi-environment deployments
""",
        "tech_stack": """
- Terraform / Bicep / CloudFormation
- Azure / AWS / GCP
- Docker & Docker Compose
- PostgreSQL (database)
- n8n (deployed infrastructure)
""",
        "tools": """
### `analyzeInfrastructure`
Scans infrastructure definition files for issues.

**Input**: `iac_path` (string), `provider` (string)
**Output**: Analysis with security and cost recommendations

### `generateTemplate`
Creates infrastructure templates for services.

**Input**: `service_type` (string), `requirements` (object)
**Output**: IaC template

### `detectDrift`
Compares actual infrastructure to defined state.

**Input**: `environment` (string)
**Output**: Drift report with remediation steps
""",
        "conventions": """
- Use modules for reusable components
- Version all infrastructure changes
- Tag all resources for cost tracking
- Implement least-privilege access
- Document all manual changes
""",
        "antipatterns": """
- ❌ Never hard-code credentials in IaC files
- ❌ Don't create untagged resources
- ❌ Avoid manual infrastructure changes
- ❌ Don't skip state locking in Terraform
""",
        "examples": """
**Example 1: Analyze infrastructure**
```
User: "InfrastructureAgent, check my n8n deployment"
Agent: *Analyzes docker-compose.yml, cloud configs*
       Found: PostgreSQL not using managed service (cost inefficiency)
       Recommendation: Migrate to Azure PostgreSQL (30% cost reduction)
```

**Example 2: Generate template**
```
User: "InfrastructureAgent, create Azure resources for n8n"
Agent: *Generates Bicep template*
       Includes: App Service, PostgreSQL, Storage, Key Vault
       *Validates security configuration*
```
""",
    },
    "testing": {
        "agent_name": "Testing & Quality Assurance Agent",
        "focus_area": "automated testing and code quality",
        "focus_domain": "test automation, coverage analysis, quality gates",
        "capabilities": """
- Run unit, integration, and e2e tests
- Generate test cases from code analysis
- Measure and report test coverage
- Identify flaky tests
- Performance benchmarking
- Code quality analysis
""",
        "tech_stack": """
- pytest (Python testing)
- Jest / Mocha (JavaScript testing)
- Coverage.py (coverage reporting)
- GitHub Actions (test automation)
- DSPy (test generation)
""",
        "tools": """
### `runTests`
Executes test suites with coverage reporting.

**Input**: `test_path` (string), `test_type` (string)
**Output**: Test results with pass/fail stats

### `generateTests`
Creates test cases based on code analysis.

**Input**: `source_file` (string), `test_framework` (string)
**Output**: Generated test file

### `analyzeCoverage`
Reports test coverage metrics.

**Input**: `coverage_data` (object)
**Output**: Coverage report with uncovered lines

### `identifyFlaky`
Detects unreliable tests.

**Input**: `test_history` (array)
**Output**: List of flaky tests with failure patterns
""",
        "conventions": """
- One test file per source file
- Use descriptive test names
- Implement test fixtures properly
- Mock external dependencies
- Maintain >80% code coverage
""",
        "antipatterns": """
- ❌ Don't write tests that depend on execution order
- ❌ Avoid testing implementation details
- ❌ Don't skip tests in CI
- ❌ Never commit failing tests
""",
        "examples": """
**Example 1: Run test suite**
```
User: "TestingAgent, run all Python tests"
Agent: *Executes pytest tests/*
       Results: 47 passed, 2 failed
       Coverage: 82% (target: 80%)
       *Generates detailed failure reports*
```

**Example 2: Generate tests**
```
User: "TestingAgent, create tests for trace_database.py"
Agent: *Analyzes agents/trace_database.py*
       *Generates tests/test_trace_database.py*
       Included: 12 test cases covering all public methods
```
""",
    },
    "security": {
        "agent_name": "Security & Compliance Agent",
        "focus_area": "security scanning and compliance verification",
        "focus_domain": "vulnerability detection, secret scanning, compliance",
        "capabilities": """
- Scan dependencies for vulnerabilities (CVEs)
- Detect exposed secrets and credentials
- Run SAST/DAST security testing
- Check compliance (SOC2, GDPR, HIPAA)
- Enforce security policies
- Generate security reports
""",
        "tech_stack": """
- GitHub Security Scanning
- Dependabot
- Secrets scanning (git-secrets, TruffleHog)
- OWASP tools
- Compliance frameworks
""",
        "tools": """
### `scanDependencies`
Checks dependencies for known vulnerabilities.

**Input**: `manifest_file` (string)
**Output**: CVE report with severity ratings

### `detectSecrets`
Scans codebase for exposed credentials.

**Input**: `scan_path` (string)
**Output**: List of found secrets with locations

### `runSAST`
Performs static application security testing.

**Input**: `source_path` (string)
**Output**: Security findings with remediation guidance

### `checkCompliance`
Verifies compliance with regulations.

**Input**: `standard` (string), `scope` (string)
**Output**: Compliance report with violations
""",
        "conventions": """
- Use environment variables for secrets
- Never commit .env files
- Rotate credentials regularly
- Implement least-privilege access
- Log security events
""",
        "antipatterns": """
- ❌ NEVER commit API keys, passwords, or tokens
- ❌ Don't disable security warnings
- ❌ Avoid using deprecated cryptography
- ❌ Don't expose internal endpoints publicly
""",
        "examples": """
**Example1: Scan for secrets**
```
User: "SecurityAgent, scan for exposed credentials"
Agent: *Scans all files recursively*
       Found: 3 potential secrets
       - .env file committed (CRITICAL)
       - API key in copilot-instructions.md (HIGH)
       *Generates remediation plan*
```

**Example 2: Check dependencies**
```
User: "SecurityAgent, audit Python dependencies"
Agent: *Analyzes requirements.txt*
       Found: 2 vulnerabilities
       - requests 2.25.0 (CVE-2023-xxxxx) → Upgrade to 2.31.0
       *Auto-creates pull request with fixes*
```
""",
    },
    "monitoring": {
        "agent_name": "Monitoring & Observability Agent",
        "focus_area": "monitoring, logging, and observability",
        "focus_domain": "monitoring dashboards, alerting, log analysis, tracing",
        "capabilities": """
- Configure monitoring dashboards
- Set up alerting rules and notifications
- Analyze logs for patterns and issues
- Implement distributed tracing
- Define and track SLOs/SLIs
- Generate observability reports
""",
        "tech_stack": """
- PostgreSQL (tracing database)
- Application Insights
- Prometheus / Grafana
- ELK Stack (Elasticsearch, Logstash, Kibana)
- OpenTelemetry
""",
        "tools": """
### `setupMonitoring`
Configures monitoring tools for services.

**Input**: `service_name` (string), `metrics` (array)
**Output**: Monitoring configuration

### `createAlerts`
Defines alerting rules.

**Input**: `alert_conditions` (object)
**Output**: Alert rules with thresholds

### `analyzeLogs`
Parses and analyzes log files.

**Input**: `log_path` (string), `timeframe` (string)
**Output**: Log analysis with patterns and anomalies

### `configureTracing`
Sets up distributed tracing.

**Input**: `service_map` (object)
**Output**: Tracing configuration

### `manageSLOs`
Defines and tracks service level objectives.

**Input**: `slo_definitions` (array)
**Output**: SLO dashboard and violation alerts
""",
        "conventions": """
- Structured logging (JSON format)
- Include correlation IDs in all logs
- Log errors with full stack traces
- Monitor critical business metrics
- Set up alerts before incidents
""",
        "antipatterns": """
- ❌ Don't log sensitive data (passwords, tokens)
- ❌ Avoid excessive logging (log aggregation costs)
- ❌ Don't ignore monitoring data
- ❌ Never disable logging in production
""",
        "examples": """
**Example 1: Analyze logs**
```
User: "MonitoringAgent, analyze n8n execution logs"
Agent: *Parses Knowledge/observability/schema.sql*
       *Queries tracing database*
       Found: 15 failed workflow executions in last hour
       Root cause: PostgreSQL connection timeout
       *Creates alert rule for future incidents*
```

**Example 2: Setup dashboard**
```
User: "MonitoringAgent, create monitoring dashboard"
Agent: *Generates dashboard configuration*
       Metrics: Workflow success rate, execution time, error rate
       Alerts: >5% error rate, >30s execution time
       *Deploys to monitoring service*
```
""",
    },
}


def create_specialized_agent(base_agents_path: str, focus: str, output_path: str):
    """Create specialized agent from base AGENTS.md"""

    if focus not in AGENT_SPECS:
        print(f"❌ Unknown focus: {focus}")
        print(f"Available: {', '.join(AGENT_SPECS.keys())}")
        return False

    spec = AGENT_SPECS[focus]
    spec["base_agents_path"] = base_agents_path

    # Generate agent file
    agent_content = AGENT_TEMPLATE.format(**spec)

    # Write output
    output_file = Path(output_path)
    output_file.parent.mkdir(parents=True, exist_ok=True)
    output_file.write_text(agent_content)

    print(f"✅ Created: {output_path}")
    print(f"   Agent: {spec['agent_name']}")
    print(f"   Focus: {spec['focus_area']}")
    return True


def main():
    parser = argparse.ArgumentParser(description="Create specialized DevOps agents")
    parser.add_argument("--base-agents", required=True, help="Path to base AGENTS.md")
    parser.add_argument(
        "--focus",
        required=True,
        choices=list(AGENT_SPECS.keys()),
        help="Focus area for specialization",
    )
    parser.add_argument(
        "--output", required=True, help="Output path for agent AGENTS.md"
    )

    args = parser.parse_args()

    success = create_specialized_agent(args.base_agents, args.focus, args.output)
    sys.exit(0 if success else 1)


if __name__ == "__main__":
    main()
