#!/usr/bin/env python3
"""Generate a human-friendly skills catalogue report from .github/skills-index.json

Writes Markdown to `reports/skills_report.md`.
"""
import json
from collections import Counter, defaultdict
from pathlib import Path


def load_index(path: Path):
    return json.loads(path.read_text())


def summarize(index):
    total = len(index)
    by_root = Counter()
    by_name_prefix = Counter()
    samples = defaultdict(list)

    for item in index:
        p = Path(item.get("path", ""))
        root = p.parts[0] if p.parts else "(root)"
        by_root[root] += 1

        name = item.get("name", "")
        prefix = name.split("-")[0] if name else "misc"
        by_name_prefix[prefix] += 1

        desc = item.get("description", "").strip()
        samples[prefix].append((name, p.as_posix(), desc))

    return {
        "total": total,
        "by_root": by_root,
        "by_name_prefix": by_name_prefix,
        "samples": samples,
    }


def render_md(summary):
    lines = []
    lines.append("# Skills Catalogue Report")
    lines.append("")
    lines.append(f"Total skills indexed: **{summary['total']}**")
    lines.append("")

    lines.append("## Top locations (by file root)")
    for root, cnt in summary["by_root"].most_common():
        lines.append(f"- **{root}**: {cnt}")
    lines.append("")

    lines.append("## Name-prefix distribution (quick thematic view)")
    for prefix, cnt in summary["by_name_prefix"].most_common(20):
        lines.append(f"- **{prefix}**: {cnt}")
    lines.append("")

    lines.append("## Example skills by theme (samples)")
    for prefix, items in sorted(summary["samples"].items(), key=lambda t: -len(t[1])):
        lines.append(f"### {prefix} (sample {len(items)})")
        for name, path, desc in items[:5]:
            desc = desc or "(no description)"
            lines.append(f"- **{name}** — {desc} — `{path}`")
        lines.append("")

    lines.append("---")
    lines.append("_Generated by `scripts/generate_skills_report.py`_")
    return "\n".join(lines)


def main():
    root = Path(__file__).resolve().parents[1]
    index_file = root / ".github" / "skills-index.json"
    out_dir = root / "reports"
    out_dir.mkdir(exist_ok=True)

    if not index_file.exists():
        print(f"Index file not found: {index_file}")
        raise SystemExit(2)

    index = load_index(index_file)
    summary = summarize(index)
    md = render_md(summary)

    out = out_dir / "skills_report.md"
    out.write_text(md)
    print(f"Wrote {out}")


if __name__ == "__main__":
    main()
