# VSCode Document Cataloging on Save
# ====================================
# Triggered: After file save (via VSCode save event or keybinding)
# Purpose: Lightweight logging of changes to Serena memory

param(
    [string]$FilePath = "",
    [switch]$Verbose = $false
)

$ErrorActionPreference = 'Continue'
$ProjectRoot = Split-Path (Split-Path $PSScriptRoot -Parent) -Parent

# If no file path provided, use current VSCode active file
if (-not $FilePath) {
    Write-Host "[Catalog] No file path provided - use with file path argument" -ForegroundColor Yellow
    exit 1
}

# Resolve to absolute path if relative
if (-not [System.IO.Path]::IsPathRooted($FilePath)) {
    $FilePath = Join-Path $ProjectRoot $FilePath
}

# ============================================================================
# 1. Validate File Path
# ============================================================================
if (-not (Test-Path $FilePath)) {
    Write-Host "[!] File not found: $FilePath" -ForegroundColor Red
    exit 1
}

$fileInfo = Get-Item $FilePath

# ============================================================================
# 2. Check if File Should Be Cataloged
# ============================================================================

# Skip excluded directories
$excludePatterns = @(
    "node_modules",
    ".git",
    "dist",
    "build",
    "out",
    ".vscode",
    "n8n-data",
    "__pycache__",
    ".pytest_cache",
    "venv",
    "env"
)

$shouldSkip = $false
foreach ($pattern in $excludePatterns) {
    if ($FilePath -like "*\$pattern\*" -or $FilePath -like "*/$pattern/*") {
        $shouldSkip = $true
        break
    }
}

if ($shouldSkip) {
    if ($Verbose) {
        Write-Host "[i] Skipping excluded path: $FilePath" -ForegroundColor DarkGray
    }
    exit 0
}

# Check if file is a catalogable type
$catalogableExtensions = @(
    ".ts", ".js", ".tsx", ".jsx",
    ".py", ".pyw",
    ".md", ".mdx",
    ".json", ".jsonc", ".yaml", ".yml", ".toml",
    ".ps1", ".sh", ".bash",
    ".cs", ".java", ".go", ".rs",
    ".html", ".css", ".scss", ".sass",
    ".sql", ".graphql",
    ".txt", ".cfg", ".conf", ".ini",
    ".dockerfile", "Dockerfile"
)

$fileExt = $fileInfo.Extension.ToLower()
$fileName = $fileInfo.Name

$isCatalogable = $catalogableExtensions -contains $fileExt -or 
$fileName -eq "Dockerfile" -or 
$fileName -like ".env*" -or
$fileName -like "*.config.*"

if (-not $isCatalogable) {
    if ($Verbose) {
        Write-Host "[i] Skipping non-catalogable file type: $fileExt" -ForegroundColor DarkGray
    }
    exit 0
}

# ============================================================================
# 3. Log Change to Serena Memory
# ============================================================================
$serenaMemoryPath = Join-Path $ProjectRoot ".serena\memories"
$changeLogPath = Join-Path $serenaMemoryPath "recent-changes.md"

# Ensure memory directory exists
if (-not (Test-Path $serenaMemoryPath)) {
    New-Item -Path $serenaMemoryPath -ItemType Directory -Force | Out-Null
}

# Create change log if it doesn't exist
if (-not (Test-Path $changeLogPath)) {
    $headerContent = @"
# Recent Changes Log
**Auto-generated by VSCode automation**
**Last updated**: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")

---

## Change History
<!-- Recent file saves are logged here automatically -->

"@
    Set-Content -Path $changeLogPath -Value $headerContent
}

# Generate relative path for cleaner logging
$relativePath = $FilePath.Replace($ProjectRoot, "").TrimStart('\', '/')

# Get file stats
$fileSize = $fileInfo.Length
$fileSizeKB = [math]::Round($fileSize / 1024, 2)

# Prepare log entry
$timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
$logEntry = "- **$timestamp** | Modified: ``$relativePath`` | Size: $fileSizeKB KB"

# Append to change log (keep last 100 entries to prevent bloat)
$existingContent = Get-Content $changeLogPath -Raw
$lines = $existingContent -split "`n"

# Find where change history starts
$historyStartIndex = 0
for ($i = 0; $i -lt $lines.Count; $i++) {
    if ($lines[$i] -like "*## Change History*") {
        $historyStartIndex = $i + 2  # Skip the comment line
        break
    }
}

# Extract header and existing entries
$header = $lines[0..$historyStartIndex] -join "`n"
$existingEntries = $lines[($historyStartIndex + 1)..($lines.Count - 1)] | Where-Object { $_ -match '^\s*-\s+\*\*' }

# Add new entry at the top and keep only last 100
$allEntries = @($logEntry) + $existingEntries | Select-Object -First 100

# Combine and save
$newContent = $header + "`n" + ($allEntries -join "`n") + "`n"
Set-Content -Path $changeLogPath -Value $newContent -NoNewline

Write-Host "[Catalog] Logged change: $relativePath" -ForegroundColor Green

# ============================================================================
# 4. Optional: Generate AI Toolkit Trace (if active)
# ============================================================================
# AI Toolkit traces are automatically captured when tracing is enabled
# No action needed here - just note it for verbose output

if ($Verbose) {
    Write-Host "[i] AI Toolkit will auto-trace if enabled" -ForegroundColor DarkGray
}

# ============================================================================
# 5. Optional: Notify Context7 (on-demand indexing)
# ============================================================================
# Context7 indexes files on-demand when queried
# No manual trigger needed

if ($Verbose) {
    Write-Host "[i] Context7 will re-index on next query" -ForegroundColor DarkGray
}

Write-Host "[OK] Cataloging complete" -ForegroundColor Cyan
exit 0
